  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position Controllers ---------------------------------------
  mtm_joint_1_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_outer_yaw_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  mtm_joint_2_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_shoulder_pitch_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  mtm_joint_3_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_elbow_pitch_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  mtm_joint_4_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_wrist_platform_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  mtm_joint_5_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_wrist_pitch_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  mtm_joint_6_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_wrist_yaw_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  mtm_joint_7_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_wrist_roll_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
