  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position Controllers ---------------------------------------
  psm_joint_1_position_controller:
    type: effort_controllers/JointPositionController
    joint: one_outer_yaw_joint
    pid: {p: 1000.0, i: 0.01, d: 150.0}

  psm_joint_2_position_controller:
    type: effort_controllers/JointPositionController
    joint: one_outer_pitch_joint_1
    pid: {p: 1000.0, i: 0.1, d: 150.0}

  psm_joint_3_position_controller:
    type: effort_controllers/JointPositionController
    joint: one_outer_pitch_joint_3
    pid: {p: 5000.0, i: 0.1, d: 150.0}

  psm_joint_4_position_controller:
    type: effort_controllers/JointPositionController
    joint: one_outer_pitch_joint_4
    pid: {p: 1000.0, i: 0.1, d: 300.0}

  psm_joint_5_position_controller:
    type: effort_controllers/JointPositionController
    joint: one_outer_pitch_joint_5
    pid: {p: 4000.0, i: 0.1, d: 300.0}

  psm_joint_6_position_controller:
    type: effort_controllers/JointPositionController
    joint: one_outer_insertion_joint
    pid: {p: 500.0, i: 0.01, d: 13.0}

  psm_joint_7_position_controller:
    type: effort_controllers/JointPositionController
    joint: one_outer_roll_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  psm_joint_8_position_controller:
    type: effort_controllers/JointPositionController
    joint: one_outer_wrist_pitch_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  psm_joint_9_position_controller:
    type: effort_controllers/JointPositionController
    joint: one_outer_wrist_yaw_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  psm_joint_10_position_controller:
    type: effort_controllers/JointPositionController
    joint: one_outer_wrist_open_angle_joint_1
    pid: {p: 100.0, i: 0.01, d: 10.0}
